FROM maven:3.6.3-openjdk-15 AS build
COPY ./ /app
WORKDIR /app
RUN mvn --show-version --update-snapshots --batch-mode clean package

FROM openjdk:11-jre-buster
RUN mkdir /app
WORKDIR /app
COPY --from=build ./target/anpr-1.0.0-SNAPSHOT.jar /app
ADD ./resources /app/resources
EXPOSE 8080
CMD ["java", "-jar", "anpr-1.0.0-SNAPSHOT.jar"]