kumuluzee:
  name: anpr
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://0.0.0.0:8081
    http:
      port: 8081
  discovery:
    etcd:
      hosts: http://etcd-service.default.svc.cluster.local:2379
    ttl: 20
    ping-interval: 15
