kumuluzee:
  name: anpr
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  discovery:
    ttl: 20
    ping-interval: 15
  config:
    consul:
      agent: 10.4.3.19:8500,10.4.4.26:8500,10.4.5.25:8500